### ISSUE TITLE
v0.4.0 plan

### ISSUE THREAD

**Issue by raiguard** [nihilistzsche/Factorio-LtnManager#124]
v0.4.0 will be a big one. While v0.3.0 brought a redesigned LTN data iterator, v0.4.0 is bringing a totally redesigned GUI. As such, there is a lot to do!

[Milestone](https://github.com/raiguard/Factorio-LtnManager/milestone/2).

## To-do
- [ ] Dispatcher status (#122)
- [x] Filtering by surface (#108)
- [x] Better search behavior (#88)
- [ ] Better handling of different networks (#86)
- [x] Network search improvements (#136)
- [ ] Enable / disable certain warnings (#60)
- [x] More sorting and search options (#51)
  - [x] Train shipments
  - [x] Station provided / requested
  - [x] Station shipments
  - [x] Station control signals
  - [x] History shipments
- [x] Open train from history (#48)
- [ ] History length setting (#127)
- [ ] "No stations found in X" alerts in GUI (#96)
- [ ] Re-introduce custom alert notifications (#131)

**Comment by raiguard** [comment]
So, an update: work on this completely fell off a cliff, because the version of my GUI framework that I was using to do this rewrite ended up being too slow and overcomplicated. This means that I have to restart again from square one with the GUI rewrite.

I will finish it eventually, but it's going to take a bit longer than I had hoped. I'm sorry!

**Comment by danyax** [comment]
@raiguard, any news on development front? I can't imagine running megabase without LTN and LTN Manager. I do hope you will not abandon this essential mod!

**Comment by raiguard** [comment]
Unfortunately, I have basically abandoned this mod. I will keep it up to date and fix outstanding crashes, but I don't know if I'll ever "finish" it. I won't make promises either way. I'm sorry.

**Comment by danyax** [comment]
Got it. Anyway good that you keeping current version bug fixed. Thank you for your hard work!

**Comment by Moonsilence** [comment]
raiguard, will this mod at least loose it's suggestive [ALPHA] tag from it's title, regardless of abandonment of the plans from October 2020?

**Comment by raiguard** [comment]
I am going to release v0.4.0 without completing all of these things, so I can get feedback on the fundamental GUI changes before I add all of the requested features.

**Comment by danyax** [comment]
Makes total sense!

**Comment by danyax** [comment]
New UI lokks cool! Larger, cleaner.

So far the only downside of new UI is inventory tab design. In old desing clickibg on material shown station list. Thus is super useful do see what is happening in your base

**Comment by raiguard** [comment]
The inventory list is no longer needed. Search for a material on the stations or trains tab and it'll show all the rows with that material.

![image](https://user-images.githubusercontent.com/3515394/142141912-e0308c6c-9247-4302-b213-19bb5bf66bab.png)

**Comment by danyax** [comment]
Let me explain user scenario that I miss. Every now and then I examine Inventory tab to  see if there shortages on materials happenув or about to happen. Clicking on resource showed in a quick way requesters that are starved or providers that have low supply. Typically I do 2-5 clicks on resources with shotages or on low supply and get overview of situation with each resource. If I need to see what is happening at specific station, I clicked station name and it opened up map (there was separate report that this feature is missing now).

In current design I would need to manually type each resource name in station tab. This is less convinient - in old design all was done on one tab with no typing. 

As partial solution clicking on resource on Inventory tab could open station tab filtered by clicked resource. Still less convinient because one have to switch back to inventory tab for each resource to be examined.

Hope this will be useful.

**Comment by Brovine** [comment]
While I love the new interface overall, it's a shame to lose the convenient summary the old interface gave when you clicked on an item in the inventory tab. I've used it the same way danyax did above, quickly clicking between items to check status and shortages to decide what to work on next. (I mostly use this in a pymods world, so there are a lot of products to sort between!)

Using the stations tab involves flipping to another tab, typing in the product i want to check in search, then sorting between a whole bunch of stations to find the shortage and check the inputs. Then I have to switch back to inventory and clear the search before I can check another product. 

Other than that though, the new inventory layout is so much easier to work with than the compact lists of the old UI, and the new trains/stations/depots tabs look great too!

**Comment by KasperHoldum** [comment]
Nice work on the update! :)

Any chance that you could also filter the count in the tabs when selecting a surface? Usage: Trying the match the number of trains with depots.
